### ISSUE TITLE
Select disabled color mismatch

### ISSUE THREAD

**Issue by Schwartz10** [glifio/safe#102]
<img width="590" alt="image" src="https://user-images.githubusercontent.com/12353734/172526119-0744044a-fadf-4667-b0d1-673ffdba58bc.png">

See here how the select input disabled grey is a tiny bit lighter than the others?

**Comment by navFooh** [comment]
Hah that is funny, the browser gives a default opacity of 0.7 to disabled `select` elements, but not to `input` elements.
I'll fix it in `base-css`
