### ISSUE TITLE
After safe creation, EXEC transaction appears always pending in the message history until logout/login

### ISSUE THREAD

**Issue by Schwartz10** [glifio/safe#104]
This transaction should either be there, and confirm (like all the others) or be hidden (like i thought it was before?)

This may be an issue with the graphQL backend, and no changes required safe-side

**Comment by Schwartz10** [comment]
This is because we push the submitted message from safe creation (so it shows pending in the UI), but the graphQL wont return an exec transaction for a multisig address (we dont get the genesis creation transaction for a new actor yet)

**Comment by navFooh** [comment]
Should we make `pushPendingMessage` optional then in the `Transaction.Form` component or is there another place where we can best solve this issue?

**Comment by Schwartz10** [comment]
I think for now, one thing we could do is just not `pushPendingMessage` if the message is a constructor message to the EXEC ACTOR. I believe this is the only case where the message won't actually appear in the actor's transaction history (since it wasn't sent from/to the actor address, the actor was created from this transaction)
