### ISSUE TITLE
Enter or create actor form - pressing "Enter" takes the user to safe home (not dashboard)

### ISSUE THREAD

**Issue by Schwartz10** [glifio/safe#117]
@navFooh do you see an issue with putting the buttons inside the form, and using the onSubmit handler in the form? https://github.com/glifio/safe/blob/primary/components/Msig/Choose.tsx#L85

**Comment by navFooh** [comment]
You're right it would be better to use the onSubmit handler on all the forms. I'll change it in the `Transaction.Form` component as well.
