### ISSUE TITLE
"Go to Safe dashboard" on creation confirmation leads to landing page

### ISSUE THREAD

**Issue by navFooh** [glifio/safe#40]
**Describe the bug**
After creating a safe, a confirmation page shows with a "Go to Safe dashboard" button. However, clicking on that button leads to the Safe landing page, not the Safe dashboard.

**To Reproduce**
1. Create a new safe
2. Click on 'Go to Safe dashboard' on the confirmation page
3. End up at the Safe landing page

**Expected behavior**
I expect to go to the Safe Dashboard, not the landing page

**Screenshots**
![image](https://user-images.githubusercontent.com/394452/155407142-6ce70665-b787-488c-80d7-875e28c6e5e2.png)

**Desktop (please complete the following information):**
- OS: Windows 10
- Browser: Chrome
- Version: 98.0.4758.102

**Comment by Schwartz10** [comment]
I can't seem to replicate this one @navFooh - i go to the safe dashboard when i click that button (where the assets tab is displayed)

**Comment by navFooh** [comment]
Tried again and it works indeed, closing the issue
