### ISSUE TITLE
Admin page 

### ISSUE THREAD

**Issue by Schwartz10** [glifio/safe#49]
feel free to spice up where you see fit

<img width="1135" alt="image" src="https://user-images.githubusercontent.com/12353734/156964856-6baabfca-858e-4ced-a4f4-759fa870381e.png">

**Comment by navFooh** [comment]
Let me know which you prefer:

Option A:

![image](https://user-images.githubusercontent.com/394452/157051303-81d5ee9a-ace5-47f4-bf97-edb7af91d24b.png)

Option B:

![image](https://user-images.githubusercontent.com/394452/157051330-5cfe6c40-eea4-4215-aa87-8c3169bb6389.png)

Option C:

![image](https://user-images.githubusercontent.com/394452/157051358-6f5ca917-25c8-4f10-87a1-a8a139a39209.png)

**Comment by Schwartz10** [comment]
Option C
